version: '2'
services:
  myjs:
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    working_dir: /usr/app
    command: node src/main.js
    
